#------------------------------------------------#
#              Theme Configuration               #
#------------------------------------------------#
[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"

#------------------------------------------------#
#              Server Configuration              #
#------------------------------------------------#
[server]
maxUploadSize=50